### ISSUE TITLE
Using Emulator via Bluetooth

### ISSUE THREAD

**Issue by Dipi24** [cabal95/Zebra-Emulator#1]
Hi,

I am trying to use this emulator. I have setup the project and also able to run it.
I am able to use via TCP seamlessly but not able to use via Bluetooth. Any additional configuration needed for this?
I am not sure whether its an issue or I am doing something wrong with the set-up. Your help is much appreciated. Thanks in advance.

**Comment by cabal95** [comment]
There shouldn't be any additional configuration - though it's always possible that there is _something_ that was already set on my computer that I'm not ware of.

Couple things you can check though.

1. If you are trying to use an iOS Simulator to connect via bluetooth that won't work if I recall. It has to be from a physical iOS device.
2. I used an iOS App called `GATT Browser` to help debug this, so you might be able to use that to verify that your computer is broadcasting correctly.
3. Zebra has an iOS app for printing test labels. I believe it also worked in my testing, so might check that one and verify it can print to the virtual printer.
4. Depending on what you are using to print from, it's very possible that I'm not 100% correctly implementing the bluetooth feature set. Zebra had very little documentation on the subject (i.e. none) so much of the implementation was built based on their public source code samples for how to connect _to_ a bluetooth printer.

**Comment by Dipi24** [comment]
Thank you for prompt response.
I am working on MacBook Pro not using any simulator. 
I am able to see my computer in other devices. 
Data part is fine but I need to test connection with bluetooth zebra printer. I don't have printer handy at this point of time so emulator would help me.

**Comment by cabal95** [comment]
What are you using to print from?  An iOS app or some dedicated piece of hardware?

Does whatever you are trying to print from _see_ the printer?

Does whatever you are trying to print from _connect_ to the printer (or said another way, does it get so far as to _try_ to connect to the printer)?

Does whatever you are trying to print from give any errors when trying to print?

I would again try to use the `GATT Browser` iOS app to verify that your computer is even broadcasting the correct GATT information.  With the Zebra Emulator running, you should be able to run GATT Browser, connect to your computer, and see a `Custom Service` with this UUID: `38EB4A80-C570-11E3-9507-0002A5D5C51B`, it should also have two services listed. If you see that, then the app is correctly broadcasting.
